language: python
python:
  - "3.6"
install:
  - pip install pylint
  - pip install -U spacy
  - python -m spacy download en
  - pip install -r requirements.txt
before_script:
  - pylint --version
script:
  - sh ./build.sh